vich_uploader:
    db_driver: orm

    mappings:
        actor_photo:
            uri_prefix: /images/actors
            upload_destination: '%kernel.project_dir%/public/images/actors'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
